// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABZYZHi4TLjDBwIqXN_zMDZUG-2G-6RBY',
    appId: '1:281463807739:web:67392d50d4c0aac0a89a5e',
    messagingSenderId: '281463807739',
    projectId: 'proxym-79243',
    authDomain: 'proxym-79243.firebaseapp.com',
    storageBucket: 'proxym-79243.firebasestorage.app',
    measurementId: 'G-ZTGR0PFXL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgEEIa3c57hlnFmcQz-zh9Qsdoq19qn6Q',
    appId: '1:281463807739:android:1196789a6436a67fa89a5e',
    messagingSenderId: '281463807739',
    projectId: 'proxym-79243',
    storageBucket: 'proxym-79243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ9kmnVClQseXovLOrfeKOvBX0GKudU9k',
    appId: '1:281463807739:ios:2578e0183a4ab3dba89a5e',
    messagingSenderId: '281463807739',
    projectId: 'proxym-79243',
    storageBucket: 'proxym-79243.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ9kmnVClQseXovLOrfeKOvBX0GKudU9k',
    appId: '1:281463807739:ios:2578e0183a4ab3dba89a5e',
    messagingSenderId: '281463807739',
    projectId: 'proxym-79243',
    storageBucket: 'proxym-79243.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABZYZHi4TLjDBwIqXN_zMDZUG-2G-6RBY',
    appId: '1:281463807739:web:d411909732b53a06a89a5e',
    messagingSenderId: '281463807739',
    projectId: 'proxym-79243',
    authDomain: 'proxym-79243.firebaseapp.com',
    storageBucket: 'proxym-79243.firebasestorage.app',
    measurementId: 'G-NJ7VLZBHEW',
  );
}
